#spring.main.banner-mode=off
#logging.level.org.springframework.cache=trace
#logging.level.com.github.benmanes=trace

spring.jackson.serialization.indent-output=true
spring.jackson.date-format=yyyy-MM-dd
